fixed table sizing with length of notes
hytech-racing/query-frontend pull request #68
Opened 2024-12-08 06:39 UTC by jyuenbeep

2024-12-09 04:39 UTC, aesteri commented on .env
> +VITE_API_URL=https://hytechracing.duckdns.org
change this back! Never push private info onto main!

2024-12-09 04:41 UTC, aesteri requested changes
Could you resolve merge conflicts? and the branch not being deployed is a bit weird, you might want to look at it!

2025-01-05 22:02 UTC, aesteri requested changes
Overall, Very Good! I'm so proud of you :))

Just tiny changes

2025-01-05 22:02 UTC, aesteri commented on src/App.tsx
You should look at how the main branch deals with utilizing main.tsx! We decided to add in new pages for changelog and documentation so this will be helpful in understanding the frontend structure :)

(so basically we are not using App.tsx anymore and it should be deleted!)

2025-01-05 22:02 UTC, aesteri commented on src/components/DataTable.tsx
> +              value="
Change this back to file.note

2025-01-05 22:02 UTC, aesteri commented on src/components/DataTable.tsx
> +              rows={4}
Can you avoid hard coding the amount of rows? Maybe make it dynamic?

2025-01-05 22:02 UTC, aesteri commented on src/components/DataTable.tsx
> +              placeholder="Note"
Maybe change this to No notes available?

something like down below
<img width="1076" alt="Screenshot 2025-01-05 at 4 59 47 PM" src="https://github.com/user-attachments/assets/f8748069-1578-4840-bd55-8f640d6d9acb" />

2025-01-12 21:48 UTC, aesteri requested changes
I reviewed the page with the leads, and they made some suggestions for us! I made some comments that go over what was discussed! You're doing great, they love how it looks xD!

2025-01-12 21:48 UTC, aesteri commented on src/components/DataTable.tsx
> +              variant="unstyled"
Can you add size="xs" to this as well as the location?

2025-01-12 21:48 UTC, aesteri commented on src/components/DataTable.tsx
>          <Table.Td>{file.location}</Table.Td>
Can u do the same for location but with maxRows of 1?

2025-01-12 21:48 UTC, aesteri commented on src/css/Root.css
> +    width: 80%;
can u make this 60% (also min-width)

2025-01-12 21:48 UTC, aesteri commented on src/css/SearchBar.css
> -  border-left: solid #D1BF80 2px;
Change back!

2025-01-12 22:04 UTC, aesteri commented on package.json
> -    "nuqs": "^2.2.1",
Might want to change this back. Im not sure if this was the exact issue but application might be loading slower because of this

2025-01-20 15:58 UTC, jyuenbeep commented on src/css/SearchBar.css
> -  border-left: solid #D1BF80 2px;
I thought SearchBar.css has stayed the same for a while? What should this be changed back to?

2025-01-20 16:03 UTC, jyuenbeep commented on src/components/DataTable.tsx
>          <Table.Td>{file.location}</Table.Td>
i think server said it was down ? but even though my channels are activated, no data points are loading so im not sure what this looks like. i used the same style for file.notes, but im not sure what it looks liek on the frontend since the data hasnt been loading since yesterday

2025-01-20 16:06 UTC, jyuenbeep commented on src/css/SearchBar.css
> -  border-left: solid #D1BF80 2px;
Oh nvm i found it

2025-01-29 00:10 UTC, aesteri submitted a review, later dismissed
LGTM!

2025-01-29 00:11 UTC, aesteri approved these changes

2025-01-29 00:22 UTC, kaisernarkotic approved these changes

2025-01-29 00:22 UTC, merged